language: java
install: true
jdk: openjdk11
cache:
  directories:
  - $HOME/.gradle/caches/
env:
  matrix:
  - TERM=dumb
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - ./gradlew --version
script: ./gradlew -S build jacocoTestReport
after_success:
  - ./gradlew coveralls

